"""Install a staged TEXTUALIZATION_REV 2 build over the live canonical directory, superseding rev1.

    python scratchpad/final_canonical_build/rev2_install.py <ds> [--stage DIR] [--dry-run]

NOTHING IS DELETED.  The rev1 build outputs are MOVED into
data/final_canonical/_superseded_textualization_rev1/<ds>/ (the same directory hotpotqa's rev1 went into on
2026-09-05), and the staged outputs are MOVED into place.  Both are renames on one volume, so a 5 GB node table
costs no copy.

Only BUILD OUTPUTS move.  Hand-written and separately-derived artifacts stay in the live directory because they
are not regenerated by the builder and are still valid across a text-only revision:
    SOURCE_CONTRACT.json          refreshed afterwards by source_contracts.py
    node_id_map_legacy.json       node ids are unchanged by definition of this revision
    legacy_comparison.json        re-derived afterwards by legacy_compare_kb.py
    EMPTY_TEXT_*                  the forensics that motivated the revision
    _superseded_* subdirectories  earlier supersessions; nesting them would hide them
reuse_map/ DOES move: its per-node digests are keyed to the canonical text, so the rev1 copy is stale by
construction and must be recomputed (reuse_map_kb.py) rather than inherited.
"""
import os, sys, json, shutil, argparse, time

ROOT = "data/final_canonical"
SUP = f"{ROOT}/_superseded_textualization_rev1"
# build outputs -- these are what a rebuild regenerates, and therefore what supersedes
MOVE = ("nodes.jsonl", "build_info.json", "integrity_report.json", "queries", "reuse_map",
        "dataset_manifest.json", "query_independence_test.json", "status.json")
EVAL_PREFIX = "eval_"          # eval_<N>.jsonl, N depends on the lane


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("ds")
    ap.add_argument("--stage", default=None)
    ap.add_argument("--dry-run", action="store_true")
    a = ap.parse_args()
    ds = a.ds
    live = f"{ROOT}/{ds}"
    stage = a.stage or f"{ROOT}/_stage_{ds}_rev2"
    dest = f"{SUP}/{ds}"

    assert os.path.isdir(live), live
    assert os.path.isfile(f"{stage}/nodes.jsonl"), f"no staged node table at {stage}"
    assert not os.path.exists(dest), f"{dest} already exists -- refusing to overwrite a supersession record"

    names = set(MOVE) | {f for f in os.listdir(live) if f.startswith(EVAL_PREFIX)}
    staged = set(os.listdir(stage))
    plan = []
    for n in sorted(names | {f for f in staged if f.startswith(EVAL_PREFIX)}):
        src_live, src_stage = f"{live}/{n}", f"{stage}/{n}"
        plan.append({"name": n, "rev1_present": os.path.exists(src_live), "rev2_present": os.path.exists(src_stage)})
    left = sorted(set(os.listdir(live)) - names)

    print(f"install {stage} -> {live}, superseding into {dest}")
    for p in plan:
        print("   %-28s rev1=%-5s rev2=%-5s" % (p["name"], p["rev1_present"], p["rev2_present"]))
    print("   stays in the live directory:", left)
    if a.dry_run:
        return

    os.makedirs(dest, exist_ok=True)
    moved_out, moved_in, missing = [], [], []
    for p in plan:                                        # 1. rev1 -> superseded
        if p["rev1_present"]:
            shutil.move(f"{live}/{p['name']}", f"{dest}/{p['name']}")
            moved_out.append(p["name"])
    for p in plan:                                        # 2. staged -> live
        if p["rev2_present"]:
            shutil.move(f"{stage}/{p['name']}", f"{live}/{p['name']}")
            moved_in.append(p["name"])
        elif p["rev1_present"]:
            missing.append(p["name"])                      # rev1 had it, rev2 does not -- must be regenerated
    leftover = sorted(os.listdir(stage)) if os.path.isdir(stage) else []
    # queries/lanes is written by query_lanes.py, not by the builder, so it travels with the superseded
    # queries/ directory and has no rev2 counterpart. Flag it explicitly rather than let it vanish silently.
    if os.path.isdir(f"{dest}/queries/lanes") and not os.path.isdir(f"{live}/queries/lanes"):
        missing.append("queries/lanes")

    rec = {"dataset": ds, "when": time.strftime("%Y-%m-%dT%H:%M:%S"), "stage": stage, "live": live,
           "superseded_into": dest, "moved_out_of_live": moved_out, "moved_into_live": moved_in,
           "NOT_REGENERATED_BY_THE_BUILD": missing,
           "NOT_REGENERATED_note": "these rev1 outputs have no rev2 counterpart yet and must be regenerated "
                                   "explicitly (reuse_map by reuse_map_kb.py, query_independence_test by qi_test.py, "
                                   "dataset_manifest by manifest.py) -- they are NOT inherited",
           "left_in_live_untouched": left, "left_in_stage": leftover, "deleted": []}
    with open(f"{dest}/INSTALL_RECORD.json", "w", encoding="utf-8") as fh:
        json.dump(rec, fh, indent=2)
    print(json.dumps({k: rec[k] for k in ("moved_out_of_live", "moved_into_live",
                                          "NOT_REGENERATED_BY_THE_BUILD", "left_in_stage")}, indent=1))


if __name__ == "__main__":
    main()
