"""L1X -- SELECT lane, step 12: the WebQSP twin of _l1x_actserve.py (generated by _mk_actserve_wq.py): how far does ONE static A^T x reach on WebQSP when it is fed more FLAT hits (ACT) and ranks a larger pool?  (development only; nothing is chosen here)
(User ruling 2026-10-01: L1 = parameter-free routing and SELECTION only -- no traversal, no fitted or learned rule.   User 2026-10-02: "try expanding metaqa oracle and improving the all coverage"; 2026-10-03 "yeah do those things ... also l1 improvements".)

The shipped IR_L1 feeds the one-hop localisation with the top ACT = 200 FLAT hits and ranks the pool O[:5000].  The reach study (probe_reach) showed the one-hop support of the top-ACT hits covers
ALL golds on 54% (ACT 200), 64% (500), 70% (1000) and 77% (3000) of the MetaQA rows, so the single-product oracle can be expanded.  Here the WHOLE routed pipeline is re-run with (ACT, POOL):
  hits         top-ACT of FLAT, weight 1/(rank+1) * g        (as shipped)
  O            RRF(FLAT, LOC), K0 = 60;  pool = O[:POOL]
  router       ES (shipped) or ES_c (typed order, the L1_TYPED_SELECT_CANDIDATE order) over V_q = hits U LOC;  count B_P(q,K): the shipped knee/alpha rule applied to the SAME hit set ('own'), or the count of the
               ACT = 200 run ('ref', i.e. the shipped count with only the order/ranking fed by more hits)
  served       SHIPPED (O) or TYP = RRF(Sro, Sri, Tin) over the pool (equal weight, K0 = 60);  a gold outside the pool is placed at its exact O position (as in _l1x_rrt_route.py)
Identities for ACT = 200, POOL = 5000: (ES, SHIPPED, own) == the stored kscale verdict on every (row, B_N) and B_P == the stored count.  Half A = even rows, half B = odd rows; everything is also split by hop.

  python -u scratchpad/_l1x_actserve_wq.py RUN webqsp <tag> [--rows=K]   -> results/L1_X/actserve_webqsp__<tag>.{json,npz}  (write-once)
  python -u scratchpad/_l1x_actserve_wq.py SHOW <tag> [K]                (prints half B, per configuration)
Identities for ACT = 200, POOL = 5000 on WebQSP: (ES, SHIPPED, own) == the stored CALIB_EVAL_WEBQSP verdict (SV__PHG__k<K>__own == #gold) and B_P == BP__PHG__k<K>__own on every row.
"""
import json
import os
import sys
import time

import numpy as np

import _l1d_lib as D
import _l1d_edgediag as E
import _l1d_route as RT
import _l1d_kscale as KS
import _l1x_feat as FE
import _l1x_relsel as RS
import _l1x_rrt as R

log = D.log
K0 = D.K0
OUT = R.OUT
MC = D.M_CURVE
NM = len(MC)
CONFIGS = [(200, 5000), (1000, 5000), (3000, 5000), (6000, 5000), (6000, 10000)]
ROUTERS = ["ES", "ES_c"]
RULES = ["SHIPPED", "TYP"]
COUNTS = ["own", "ref"]


def run():
    a = [x for x in sys.argv[1:] if not x.startswith("--")]
    assert len(a) == 3 and a[0] == "RUN" and a[1] == "webqsp", __doc__
    ds, tag = a[1], a[2]
    rows_limit = next((int(x.split("=", 1)[1]) for x in sys.argv if x.startswith("--rows=")), None)
    fo = os.path.join(OUT, "actserve_%s__%s" % (ds, tag))
    assert rows_limit is not None or not os.path.exists(fo + ".json"), "write-once: %s exists" % fo
    t_all = time.time()
    me = os.path.abspath(__file__)
    cd = D.AD.CanonicalDataset(ds)
    N = int(cd.n_nodes)
    pop = FE.population(cd, rows_limit)
    nq, gptr = pop.nq, pop.gptr
    F, _ = FE.families(cd, N)
    s, d, r, ent = cd.family("structural")
    s, d, r = np.asarray(s, np.int64), np.asarray(d, np.int64), np.asarray(r, np.int64)
    nrel = len(ent.get("relation_vocabulary") or [])
    xO, aO, rO = RS.csr_by(s, d, r, N)
    xI, aI, rI = RS.csr_by(d, s, r, N)
    pIn, relIn = RS.profile(d, r, N, nrel)
    del s, d, r
    RM = RS.relation_matrix(ds, nrel)
    cells = R.CELLS[ds]
    maps = R.load_maps(cd, ds)
    tabs = {K: KS.mult_tables(K)[0][R.ALPHA] for K in cells}
    log("L1X actserve %s %s: N %d, %d rows, cells %s, configs %s" % (ds, tag, N, nq, cells, CONFIGS))
    cz = np.load(R.CALIB)
    ngo = np.diff(gptr)
    BP_ST = {K: cz["BP__PHG__k%d__own" % K][:nq] for K in cells}
    SV_ST = {K: cz["SV__PHG__k%d__own" % K][:nq] == ngo[:, None] for K in cells}
    Qu = D.unit_queries(cd, pop.rows)
    ALL = {(c, K, cv, rv, ru): np.zeros((nq, NM), bool) for c in CONFIGS for K in cells for cv in COUNTS for rv in ROUTERS for ru in RULES}
    BPQ = {(c, K): np.zeros(nq, np.int32) for c in CONFIGS for K in cells}
    SUPN = {c: np.zeros(nq, np.int64) for c in CONFIGS}
    POOLCOV = {c: np.zeros(nq, bool) for c in CONFIGS}          # every gold inside the pool
    H100 = maps[R.K_REF]
    t0 = time.time()
    ckf = os.path.join(D.REPO, "data", "_cache", "actserve_%s__%s.partial.npz" % (ds, tag))
    me_sha = D.sha_file(os.path.abspath(__file__))
    done = 0
    if rows_limit is None and os.path.exists(ckf):
        with np.load(ckf) as z:                                             # closed before the next checkpoint replaces the file (Windows refuses to replace an open file)
            assert (z["rows"] == pop.rows).all() and str(z["code_sha"]) == me_sha and int(z["CQ"]) == int(D.CQ), "stale checkpoint %s" % ckf
            done = int(z["done"])
            for k_ in ALL:
                ALL[k_] = z["ALL__%d_%d__%d__%s__%s__%s" % (k_[0][0], k_[0][1], k_[1], k_[2], k_[3], k_[4])].copy()
            for k_ in BPQ:
                BPQ[k_] = z["BPQ__%d_%d__%d" % (k_[0][0], k_[0][1], k_[1])].copy()
            for c_ in CONFIGS:
                SUPN[c_] = z["SUPN__%d_%d" % c_].copy()
                POOLCOV[c_] = z["POOLCOV__%d_%d" % c_].copy()
        log("RESUME from %s: %d / %d rows already done" % (ckf, done, nq))
    for j0, j1, SD, SS, sec, _ in (D.batches(cd, pop.rows[done:], Qu[done:], N) if done < nq else ()):
        j0, j1 = j0 + done, j1 + done
        for i in range(j1 - j0):
            j = j0 + i
            of, od, os_, npos, fv, frank = D.flat_row(SD[i], SS[i])
            g = pop.golds[j]
            cs = RM @ Qu[j].astype(np.float32)
            rr = np.empty(nrel, np.int64)
            rr[np.argsort(-cs, kind="stable")] = np.arange(nrel)
            w = 1.0 / (1.0 + rr)

            def tmax(ptr, rels, nodes):
                s2 = ptr[nodes]
                ln = ptr[nodes + 1] - s2
                out = np.zeros(len(nodes))
                if ln.sum() > 0:
                    h_, p_ = E.entries(s2, ln)
                    np.maximum.at(out, h_, w[rels[p_]])
                return out
            b_ref = {}
            for ci, cfg in enumerate(CONFIGS):
                ACT, POOL = cfg
                top = of[:ACT]
                nh = len(top)
                wseed = 1.0 / np.arange(1.0, nh + 1.0)
                U, H, GW = [], [], []
                for f in FE.FAMS:
                    Fm = F[f]
                    s_ = Fm["xadj"][top]
                    hit, pos = E.entries(s_, Fm["xadj"][top + 1] - s_)
                    U.append(Fm["adj"][pos].astype(np.int64))
                    H.append(hit)
                    GW.append(Fm["g"][top][hit])
                u, hit, gw = np.concatenate(U), np.concatenate(H), np.concatenate(GW)
                x = wseed[hit] * gw
                L = np.bincount(u, weights=x, minlength=N)
                Lord = D.order_from_score(L, frank)
                SUPN[cfg][j] = int(np.count_nonzero(L > 0))
                f_ = 1.0 / (K0 + frank.astype(np.float64))
                f_[Lord] += 1.0 / (K0 + np.arange(len(Lord), dtype=np.float64))
                FO = np.lexsort((frank, -f_))
                frk = np.empty(N, np.int64)
                frk[FO] = np.arange(N)
                pool = FO[:POOL]
                pg = frk[g]
                POOLCOV[cfg][j] = bool((pg < POOL).all())
                # ---- the router's node order O' (ES) and the typed variant (ES_c) over V_q, exactly as _l1x_rrt_route.py
                vq = np.union1d(top, Lord)
                fq = np.zeros(len(vq))
                tq = np.zeros(len(vq))
                it = np.searchsorted(vq, top)
                fq[it] += 1.0 / (K0 + np.arange(nh, dtype=np.float64))
                il = np.searchsorted(vq, Lord)
                fq[il] += 1.0 / (K0 + np.arange(len(Lord), dtype=np.float64))
                tq[il] = ACT + np.arange(len(Lord))
                tq[it] = np.arange(nh)
                perm = np.lexsort((tq, -fq))
                oq = vq[perm]
                xh = wseed * F["STRUCT_out"]["g"][top]
                xhi = wseed * F["STRUCT_in"]["g"][top]
                s_ = xO[top]
                hO, pO = E.entries(s_, xO[top + 1] - s_)
                sro = np.bincount(aO[pO].astype(np.int64), weights=xh[hO] * w[rO[pO].astype(np.int64)], minlength=N)
                s_ = xI[top]
                hI, pI = E.entries(s_, xI[top + 1] - s_)
                sri = np.bincount(aI[pI].astype(np.int64), weights=xhi[hI] * w[rI[pI].astype(np.int64)], minlength=N)
                vo = oq

                def vrank(v):
                    o_ = np.argsort(-v, kind="stable")
                    rk_ = np.empty(len(vo), np.int64)
                    rk_[o_] = np.arange(len(vo))
                    return rk_
                typs = sum(1.0 / (K0 + vrank(v)) for v in (sro[vo], sri[vo], tmax(pIn, relIn, vo)))
                rt_vq = np.empty(len(vq), np.int64)
                rt_vq[perm] = vrank(typs)
                OQ = {"ES": oq, "ES_c": vq[np.lexsort((tq, -1.0 / (K0 + rt_vq)))]}
                # ---- the served order over the pool: SHIPPED (identity) and TYP = RRF(Sro, Sri, Tin)
                S = np.zeros(POOL)
                for v in (sro[pool], sri[pool], tmax(pIn, relIn, pool)):
                    o = np.argsort(-v, kind="stable")
                    rk = np.empty(POOL, np.int64)
                    rk[o] = np.arange(POOL)
                    S += 1.0 / (K0 + rk)
                NI = np.empty((2, POOL), np.int64)
                NI[0] = np.arange(POOL)
                NI[1][np.argsort(-S, kind="stable")] = np.arange(POOL)
                gin = pg < POOL
                pgc = np.minimum(pg, POOL - 1)
                GN = NI[:, pgc]
                # ---- the count B_P(q, K): own = knee of this hit set; ref = the ACT = 200 run
                Cm = np.bincount(hit * R.K_REF + H100[u], weights=x, minlength=nh * R.K_REF).reshape(nh, R.K_REF)
                kn_, npz_ = RT.knee(wseed @ (Cm > 0))
                b0 = kn_ if npz_ else R.K_REF
                for K in cells:
                    hard = maps[K]
                    b = K if not npz_ else int(tabs[K][b0])
                    if ci == 0:
                        b_ref[K] = b
                        assert b == BP_ST[K][j], "B_P differs from the stored record (K %d row %d: %d vs %d)" % (K, j, b, BP_ST[K][j])
                    BPQ[(cfg, K)][j] = b
                    hg = hard[g]
                    cT_full = None
                    for rv in ROUTERS:
                        hq = hard[OQ[rv]]
                        up, first = np.unique(hq, return_index=True)
                        fe = np.full(K, len(OQ[rv]), np.int64)
                        fe[up] = first
                        ro = np.lexsort((np.arange(K), fe))
                        for cv in COUNTS:
                            bb = b if cv == "own" else b_ref[K]
                            cm = np.zeros(K, bool)
                            cm[ro[:bb]] = True
                            if not cm[hg].all():
                                continue
                            cp = cm[hard[pool]]
                            cT = np.cumsum(cm[hard[FO[:max(int(pg.max()) + 1, POOL)]]]) - 1
                            tail = cT[np.minimum(pg, len(cT) - 1)]
                            CPN = np.zeros((2, POOL), np.int32)
                            CPN[np.arange(2)[:, None], NI] = cp[None, :]
                            CN = np.cumsum(CPN, axis=1) - 1
                            rp = np.where(gin[None, :], np.take_along_axis(CN, GN, axis=1), tail[None, :])
                            mx = rp.max(axis=1)
                            for ri, ru in enumerate(RULES):
                                ALL[(cfg, K, cv, rv, ru)][j] = mx[ri] < np.array(MC)
        if rows_limit is None:
            ck = {"rows": pop.rows, "done": np.int64(j1), "code_sha": np.array(me_sha), "CQ": np.int64(D.CQ)}
            for k_, v_ in ALL.items():
                ck["ALL__%d_%d__%d__%s__%s__%s" % (k_[0][0], k_[0][1], k_[1], k_[2], k_[3], k_[4])] = v_
            for k_, v_ in BPQ.items():
                ck["BPQ__%d_%d__%d" % (k_[0][0], k_[0][1], k_[1])] = v_
            for c_ in CONFIGS:
                ck["SUPN__%d_%d" % c_] = SUPN[c_]
                ck["POOLCOV__%d_%d" % c_] = POOLCOV[c_]
            os.makedirs(os.path.dirname(ckf), exist_ok=True)
            np.savez(ckf + ".tmp.npz", **ck)
            os.replace(ckf + ".tmp.npz", ckf)
        log("  rows %d / %d (%.0fs)" % (j1, nq, time.time() - t0))
    ident = {}
    for K in cells:
        bad = int((SV_ST[K] != ALL[((200, 5000), K, "own", "ES", "SHIPPED")]).sum())
        ident[str(K)] = {"mismatching_(row,B_N)_cells": bad, "of": int(SV_ST[K].size)}
        assert bad == 0, "shipped (ES, SHIPPED, ACT 200) routed ALL differs from the stored verdict (K %d: %d cells)" % (K, bad)
    log("identities: " + json.dumps(ident))
    A, B = (pop.rows % 2) == 0, (pop.rows % 2) == 1
    hops = np.asarray(pop.hops[:nq]) if getattr(pop, "hops", None) is not None else np.zeros(nq, np.int64)
    res = {"mode": "L1X_ACT_SERVE (development; descriptive; nothing chosen)", "definitions": __doc__, "dataset": ds, "tag": tag, "N": N, "n_rows": nq, "cells": [str(K) for K in cells],
           "configs": [list(c) for c in CONFIGS], "routers": ROUTERS, "rules": RULES, "counts": COUNTS, "budgets": list(MC), "identity_vs_stored": ident,
           "rows_A": int(A.sum()), "rows_B": int(B.sum()), "table": {}, "per_hop_all_rows": {}, "support_mean": {}, "pool_all_gold_coverage": {}, "mean_B_P": {}}
    for c in CONFIGS:
        cn = "%d|%d" % c
        res["support_mean"][cn] = round(float(SUPN[c].mean()), 1)
        res["pool_all_gold_coverage"][cn] = {"all": round(float(POOLCOV[c].mean()), 4), "by_hop": {str(h): round(float(POOLCOV[c][hops == h].mean()), 4) for h in sorted(set(hops.tolist()))}}
        for K in cells:
            res["mean_B_P"]["%s|%d" % (cn, K)] = round(float(BPQ[(c, K)].mean()), 2)
            for cv in COUNTS:
                for rv in ROUTERS:
                    for ru in RULES:
                        M = ALL[(c, K, cv, rv, ru)]
                        key = "%s|%d|%s|%s|%s" % (cn, K, cv, rv, ru)
                        res["table"][key] = {"A": [round(float(M[A, mi].mean()), 4) for mi in range(NM)], "B": [round(float(M[B, mi].mean()), 4) for mi in range(NM)]}
                        res["per_hop_all_rows"][key] = {str(h): [round(float(M[hops == h, mi].mean()), 4) for mi in range(NM)] for h in sorted(set(hops.tolist()))}
    res["seconds"] = round(time.time() - t_all, 1)
    res["code"] = {"path": D.rel(me), "sha256": D.sha_file(me)}
    res["pinned"] = D.PINNED
    if rows_limit is not None:
        log("SMOKE (--rows): identities passed; not writing")
        return
    arrays = {"rows": pop.rows, "hops": hops}
    for k_, v_ in ALL.items():
        arrays["ALL__%d_%d__%d__%s__%s__%s" % (k_[0][0], k_[0][1], k_[1], k_[2], k_[3], k_[4])] = np.packbits(v_, axis=1)
    np.savez_compressed(fo + ".npz", **arrays)
    res["npz"] = {"path": os.path.basename(fo + ".npz"), "sha256": D.sha_file(fo + ".npz")}
    D.G.S.wj(fo + ".json", res)
    log("done (%.0fs) -> %s" % (time.time() - t_all, fo))


def show():
    tag = sys.argv[2]
    Ks = sys.argv[3].split(",") if len(sys.argv) > 3 else None
    rec = json.load(open(os.path.join(OUT, "actserve_webqsp__%s.json" % tag), encoding="utf-8"))
    print("WebQSP routed ALL, half B (n=%d), B_N %s" % (rec["rows_B"], rec["budgets"]))
    for K in (Ks or rec["cells"]):
        base = rec["table"]["200|5000|%s|own|ES|SHIPPED" % K]["B"]
        print("K %s" % K)
        for c in rec["configs"]:
            cn = "%d|%d" % tuple(c)
            for cv in rec["counts"]:
                if cn == "200|5000" and cv == "ref":
                    continue
                for ru, rv in (("SHIPPED", "ES"), ("TYP", "ES_c")):
                    v = rec["table"]["%s|%s|%s|%s|%s" % (cn, K, cv, rv, ru)]["B"]
                    print("  ACT %4d POOL %5d count %-3s %-4s %-7s %s | d vs shipped %s | pool-all-gold %.3f support %.0f" % (
                        c[0], c[1], cv, rv, ru, " ".join("%.3f" % t for t in v), " ".join("%+.3f" % (t - u_) for t, u_ in zip(v, base)), rec["pool_all_gold_coverage"][cn]["all"], rec["support_mean"][cn]))
        print("  per hop (all rows) at B_N = 1000:")
        for c in rec["configs"]:
            cn = "%d|%d" % tuple(c)
            ph = rec["per_hop_all_rows"]["%s|%s|own|ES_c|TYP" % (cn, K)]
            print("    ACT %4d POOL %5d ES_c/TYP own: %s" % (c[0], c[1], " ".join("hop%s %.3f" % (h, v[3]) for h, v in ph.items())))


if __name__ == "__main__":
    if sys.argv[1] == "RUN":
        run()
    elif sys.argv[1] == "SHOW":
        show()
    else:
        raise SystemExit(__doc__)
