"""One-off generator: derive scratchpad/_l1x_actserve_wq.py (WebQSP ACT/POOL reach study) from scratchpad/_l1x_actserve.py by exact text substitution.
Every substitution must match exactly once; the identity block is the one _l1x_rrt.py / _l1x_rrt_route.py use for WebQSP (CALIB_EVAL BP__PHG / SV__PHG)."""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
src = open(os.path.join(HERE, "_l1x_actserve.py"), encoding="utf-8").read()


def sub(old, new, count=1):
    global src
    assert src.count(old) == count, (src.count(old), old[:80])
    src = src.replace(old, new)


sub('''"""L1X -- SELECT lane, step 11: how far does ONE static A^T x reach on MetaQA when it is fed more FLAT hits (ACT) and ranks a larger pool?  (development only; nothing is chosen here)''',
    '''"""L1X -- SELECT lane, step 12: the WebQSP twin of _l1x_actserve.py (generated by _mk_actserve_wq.py): how far does ONE static A^T x reach on WebQSP when it is fed more FLAT hits (ACT) and ranks a larger pool?  (development only; nothing is chosen here)''')
sub('''"try expanding metaqa oracle and improving the all coverage".)''', '''"try expanding metaqa oracle and improving the all coverage"; 2026-10-03 "yeah do those things ... also l1 improvements".)''')
sub('''  python -u scratchpad/_l1x_actserve.py RUN metaqa <tag> [--rows=K]     -> results/L1_X/actserve_metaqa__<tag>.{json,npz}  (write-once)
  python -u scratchpad/_l1x_actserve.py SHOW <tag> [K]                  (prints half B, per configuration, and the per-hop split at B_N = 1000)''',
    '''  python -u scratchpad/_l1x_actserve_wq.py RUN webqsp <tag> [--rows=K]   -> results/L1_X/actserve_webqsp__<tag>.{json,npz}  (write-once)
  python -u scratchpad/_l1x_actserve_wq.py SHOW <tag> [K]                (prints half B, per configuration)
Identities for ACT = 200, POOL = 5000 on WebQSP: (ES, SHIPPED, own) == the stored CALIB_EVAL_WEBQSP verdict (SV__PHG__k<K>__own == #gold) and B_P == BP__PHG__k<K>__own on every row.''')
sub('CONFIGS = [(200, 5000), (500, 5000), (1000, 5000), (1000, 10000), (3000, 5000), (3000, 20000)]',
    'CONFIGS = [(200, 5000), (1000, 5000), (3000, 5000), (6000, 5000), (6000, 10000)]')
sub('assert len(a) == 3 and a[0] == "RUN" and a[1] == "metaqa", __doc__', 'assert len(a) == 3 and a[0] == "RUN" and a[1] == "webqsp", __doc__')
sub('fo = os.path.join(OUT, "actserve_%s__%s" % (ds, tag))', 'fo = os.path.join(OUT, "actserve_%s__%s" % (ds, tag))')
sub('''    st = np.load(os.path.join(D.OUT, "kscale_metaqa__v1.npz"))
    assert (st["rows"][:nq] == pop.rows).all()
    BP_ST = {K: st["CNTA__PHG_k%d" % K][:nq, 1] for K in cells}
    SV_ST = {K: np.stack([(st["LOES__PHG_k%d" % K][:nq] <= BP_ST[K]) & (BP_ST[K] <= st["HIES__PHG_k%d" % K][:nq, mi]) for mi in range(NM)], axis=1) for K in cells}
''', '''    cz = np.load(R.CALIB)
    ngo = np.diff(gptr)
    BP_ST = {K: cz["BP__PHG__k%d__own" % K][:nq] for K in cells}
    SV_ST = {K: cz["SV__PHG__k%d__own" % K][:nq] == ngo[:, None] for K in cells}
''')
sub('''    rec = json.load(open(os.path.join(OUT, "actserve_metaqa__%s.json" % tag), encoding="utf-8"))
    print("MetaQA routed ALL, half B (n=%d), B_N %s" % (rec["rows_B"], rec["budgets"]))''',
    '''    rec = json.load(open(os.path.join(OUT, "actserve_webqsp__%s.json" % tag), encoding="utf-8"))
    print("WebQSP routed ALL, half B (n=%d), B_N %s" % (rec["rows_B"], rec["budgets"]))''')
sub("    hops = np.asarray(pop.hops[:nq])\n", "    hops = np.asarray(pop.hops[:nq]) if getattr(pop, \"hops\", None) is not None else np.zeros(nq, np.int64)\n")
# ---- resumable (the host is shared and preempts; the first un-checkpointed run was lost to an mpr preemption at row ~250): after every product batch the finished rows are checkpointed, a restart skips them
sub('''    t0 = time.time()
    for j0, j1, SD, SS, sec, _ in D.batches(cd, pop.rows, Qu, N):
        for i in range(j1 - j0):
''', '''    t0 = time.time()
    ckf = os.path.join(D.REPO, "data", "_cache", "actserve_%s__%s.partial.npz" % (ds, tag))
    me_sha = D.sha_file(os.path.abspath(__file__))
    done = 0
    if rows_limit is None and os.path.exists(ckf):
        with np.load(ckf) as z:                                             # closed before the next checkpoint replaces the file (Windows refuses to replace an open file)
            assert (z["rows"] == pop.rows).all() and str(z["code_sha"]) == me_sha and int(z["CQ"]) == int(D.CQ), "stale checkpoint %s" % ckf
            done = int(z["done"])
            for k_ in ALL:
                ALL[k_] = z["ALL__%d_%d__%d__%s__%s__%s" % (k_[0][0], k_[0][1], k_[1], k_[2], k_[3], k_[4])].copy()
            for k_ in BPQ:
                BPQ[k_] = z["BPQ__%d_%d__%d" % (k_[0][0], k_[0][1], k_[1])].copy()
            for c_ in CONFIGS:
                SUPN[c_] = z["SUPN__%d_%d" % c_].copy()
                POOLCOV[c_] = z["POOLCOV__%d_%d" % c_].copy()
        log("RESUME from %s: %d / %d rows already done" % (ckf, done, nq))
    for j0, j1, SD, SS, sec, _ in (D.batches(cd, pop.rows[done:], Qu[done:], N) if done < nq else ()):
        j0, j1 = j0 + done, j1 + done
        for i in range(j1 - j0):
''')
sub('''        log("  rows %d / %d (%.0fs)" % (j1, nq, time.time() - t0))
    ident = {}
''', '''        if rows_limit is None:
            ck = {"rows": pop.rows, "done": np.int64(j1), "code_sha": np.array(me_sha), "CQ": np.int64(D.CQ)}
            for k_, v_ in ALL.items():
                ck["ALL__%d_%d__%d__%s__%s__%s" % (k_[0][0], k_[0][1], k_[1], k_[2], k_[3], k_[4])] = v_
            for k_, v_ in BPQ.items():
                ck["BPQ__%d_%d__%d" % (k_[0][0], k_[0][1], k_[1])] = v_
            for c_ in CONFIGS:
                ck["SUPN__%d_%d" % c_] = SUPN[c_]
                ck["POOLCOV__%d_%d" % c_] = POOLCOV[c_]
            os.makedirs(os.path.dirname(ckf), exist_ok=True)
            np.savez(ckf + ".tmp.npz", **ck)
            os.replace(ckf + ".tmp.npz", ckf)
        log("  rows %d / %d (%.0fs)" % (j1, nq, time.time() - t0))
    ident = {}
''')
dst = os.path.join(HERE, "_l1x_actserve_wq.py")
assert not os.path.exists(dst), "write-once"
open(dst, "w", encoding="utf-8", newline="\n").write(src)
print("wrote", dst, len(src))
